name: Inject Data about new service

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Service name'
        type: string
      description:
        description: 'Service description'
        type: string
      links:
        description: 'Service links'
        type: Array<Object>
        items:
          type: object
          properties:
            name:
              type: string
            url:
              type: string
      tags:
        description: 'Service tags'
        type: Array<string>
      rating:
        description: 'Service rating'
        type: float

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract JSON Data and Update paphos.json
        run: |
          jq --argjson data '${{ toJSON(inputs) }}' '. += [$data]' paphos.json > temp.json && mv temp.json paphos.json
        shell: bash

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: 'Add new service information'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: relocationguideguru
          reviewers: relocationguideguru
          team-reviewers: |
            SandakovMM
          milestone: 1
          draft: false