name: Dispatch Workflow
on:
  repository_dispatch:
    types: [my-custom-event]

jobs:
  customDispatchJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a custom script
        run: echo "Repository dispatch event received!"